---
- name: Deploy NextDNS and Dnsmasq (LXC Optimized)
  hosts: dns_servers
  become: true

  roles:
    - role: common
      vars:
        common_extra_packages: [dnsmasq, debian-archive-keyring, dnsutils]
        common_manage_locale: false
    - dns_server
