- name: Enable en_US.UTF-8 locale
  lineinfile:
    path: /etc/locale.gen
    regexp: '^# en_US.UTF-8 UTF-8'
    line: 'en_US.UTF-8 UTF-8'
  register: locale_gen_result

- name: Generate locales
  command: locale-gen
  when: locale_gen_result.changed
